------------------------------- TABLE DROP ------------------------------
DROP TABLE MEMBER;
DROP TABLE ADMIN;
DROP TABLE REVIEWBOARD;
DROP TABLE CONSULTANT;
DROP TABLE INTERIOR_PRODUCT;
DROP TABLE NOTICEBOARD;
--------------------------------- MEMBER ---------------------------------
CREATE TABLE MEMBER (
    mID VARCHAR2(100) PRIMARY KEY,
    mPW VARCHAR2(100) NOT NULL,
    mNAME VARCHAR2(100) NOT NULL,
    mTEL VARCHAR2(100),
    mBIRTH DATE,
    mEMAIL VARCHAR2(100),
    mGENDER VARCHAR2(5),
    mADDRESS VARCHAR2(100),
    mRDATE DATE DEFAULT SYSDATE NOT NULL
);
SELECT * FROM MEMBER;
CREATE TABLE ADMIN (
    aID VARCHAR2(100) PRIMARY KEY,
    aPW VARCHAR2(100) NOT NULL,
    aNAME VARCHAR2(100) NOT NULL
);
SELECT * FROM ADMIN;
CREATE TABLE CONSULTANT (
    cID NUMBER(6) PRIMARY KEY,
    cTITLE VARCHAR2(250) NOT NULL,
    cCONTENT VARCHAR2(4000),
    cFILENAME VARCHAR2(100),
    cRDATE DATE DEFAULT SYSDATE,
    cGROUP NUMBER(6) NOT NULL,
    cSTEP NUMBER(6) NOT NULL,
    cINDENT NUMBER(6) NOT NULL,
    cIP VARCHAR2(30) NOT NULL,
    mID VARCHAR2(100),
    aID VARCHAR2(100),
    FOREIGN KEY (mID) REFERENCES MEMBER (mID),
    FOREIGN KEY (aID) REFERENCES ADMIN (aID)
);
SELECT * FROM CONSULTANT;
CREATE TABLE REVIEW_BOARD(
    rID NUMBER(6) PRIMARY KEY,
    rTITLE VARCHAR2(250) NOT NULL,
    rCONTENT VARCHAR2(4000) NOT NULL,
    rDATE DATE DEFAULT SYSDATE,
    rHIT NUMBER(6) DEFAULT 0,
    rIP VARCHAR2(30) NOT NULL,
    mID VARCHAR2(100) NOT NULL,
    FOREIGN KEY (mID) REFERENCES MEMBER (mID)
);
SELECT * FROM REVIEW_BOARD;
CREATE TABLE INTERIOR_PRODUCT (
    pID NUMBER(6) PRIMARY KEY,
    pTITLE VARCHAR2(250) NOT NULL,
    pCONTENT VARCHAR2(4000) NOT NULL,
    pFILENAME VARCHAR2(100),
    pRDATE DATE DEFAULT SYSDATE,
    aID VARCHAR2(100) NOT NULL,
    FOREIGN KEY (aID) REFERENCES ADMIN (aID)
);
SELECT * FROM INTERIOR_PRODUCT;
CREATE TABLE NOTICE_BOARD (
    nID NUMBER(6) PRIMARY KEY,
    nTITLE VARCHAR2(250) NOT NULL,
    nCONTENT VARCHAR2(4000) NOT NULL,
    nDATE DATE DEFAULT SYSDATE,
    aID VARCHAR2(100) NOT NULL,
    FOREIGN KEY (aID) REFERENCES ADMIN (aID)
);
SELECT * FROM NOTICE_BOARD;
COMMIT;